# Generated by Django 2.2.9 on 2020-01-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=3)),
                ('student_cnt', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=50)),
            ],
        ),
    ]
