# Generated by Django 2.2.9 on 2020-01-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(max_length=30),
        ),
    ]
