# Generated by Django 2.2.9 on 2020-01-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200125_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher_name',
        ),
    ]
